const languages = [
  { no: "0", name: "Auto", native: "Detect", code: "auto" },
  { no: "1", name: "Abkhazian", native: "Аҧсуа", code: "ab" },
  { no: "2", name: "Acehnese", native: "Acèh", code: "ace" },
  { no: "3", name: "Acoli", native: "Acoli", code: "ach" },
  { no: "4", name: "Afar", native: "Afar", code: "aa" },
  { no: "5", name: "Afrikaans", native: "Afrikaans", code: "af" },
  { no: "6", name: "Akan", native: "Akan", code: "ak" },
  { no: "7", name: "Albanian", native: "Shqip", code: "sq" },
  { no: "8", name: "Alur", native: "Alur", code: "alr" },
  { no: "9", name: "Amharic", native: "አማርኛ", code: "am" },
  { no: "10", name: "Arabic", native: "عربي", code: "ar" },
  { no: "11", name: "Armenian", native: "Հայերէն", code: "hy" },
  { no: "12", name: "Assamese", native: "অসমীয়া", code: "as" },
  { no: "13", name: "Avaric", native: "Авар", code: "av" },
  { no: "14", name: "Awadhi", native: "अवधी", code: "awa" },
  { no: "15", name: "Aymara", native: "Aymar aru", code: "ay" },
  { no: "16", name: "Azerbaijani", native: "Azərbaycanca", code: "az" },
  { no: "17", name: "Balinese", native: "Basa Bali", code: "ban" },
  { no: "18", name: "Baluchi", native: "بلوچی", code: "bal" },
  { no: "19", name: "Bambara", native: "Bamanankan", code: "bm" },
  { no: "20", name: "Bangla", native: "বাংলা", code: "bn" },
  { no: "21", name: "Baoulé", native: "Baoulé", code: "ba" },
  { no: "22", name: "Bashkir", native: "Башҡорт", code: "ba" },
  { no: "23", name: "Basque", native: "Euskara", code: "eu" },
  { no: "24", name: "Batak Karo", native: "Basa Karo", code: "kbl" },
  { no: "25", name: "Batak Simalungun", native: "Basa Simalungun", code: "sim" },
  { no: "26", name: "Batak Toba", native: "Basa Toba", code: "tob" },
  { no: "27", name: "Belarusian", native: "Беларуская", code: "be" },
  { no: "28", name: "Bemba", native: "Bemba", code: "bem" },
  { no: "29", name: "Betawi", native: "Betawi", code: "bew" },
  { no: "30", name: "Bhojpuri", native: "भोजपुरी", code: "bho" },
  { no: "31", name: "Bikol", native: "Bikol", code: "bik" },
  { no: "32", name: "Bosnian", native: "Bosanski", code: "bs" },
  { no: "33", name: "Breton", native: "Brezhoneg", code: "br" },
  { no: "34", name: "Bulgarian", native: "Български", code: "bg" },
  { no: "35", name: "Buriat", native: "Буряад", code: "bu" },
  { no: "36", name: "Burmese", native: "မြန်မာစာ", code: "my" },
  { no: "37", name: "Cantonese", native: "廣東話", code: "yue" },
  { no: "38", name: "Catalan", native: "Català", code: "ca" },
  { no: "39", name: "Cebuano", native: "Cebuano", code: "ceb" },
  { no: "40", name: "Central Kurdish", native: "Kurdî", code: "ckb" },
  { no: "41", name: "Chamorro", native: "Chamoru", code: "ch" },
  { no: "42", name: "Chechen", native: "Нохчийн", code: "ce" },
  { no: "43", name: "Chiga", native: "Chiga", code: "cgg" },
  { no: "44", name: "Chinese (Simplified)", native: "中文简体", code: "zh-CN" },
  { no: "45", name: "Chinese (Traditional)", native: "中文繁體", code: "zh-TW" },
  { no: "46", name: "Chuukese", native: "Chuukese", code: "chk" },
  { no: "47", name: "Chuvash", native: "Чӑваш", code: "cv" },
  { no: "48", name: "Corsican", native: "Corsu", code: "co" },
  { no: "49", name: "Crimean Tatar", native: "Qırımtatar", code: "crh" },
  { no: "50", name: "Croatian", native: "Hrvatski", code: "hr" },
  { no: "51", name: "Czech", native: "Čeština", code: "cs" },
  { no: "52", name: "Danish", native: "Dansk", code: "da" },
  { no: "53", name: "Dari", native: "دری", code: "fa-AF" },
  { no: "54", name: "Dinka", native: "Dinka", code: "din" },
  { no: "55", name: "Divehi", native: "ދިވެހި", code: "dv" },
  { no: "56", name: "Dogri", native: "डोगरी", code: "doi" },
  { no: "57", name: "Dombe", native: "Dombe", code: "dmb" },
  { no: "58", name: "Dutch", native: "Nederlands", code: "nl" },
  { no: "59", name: "Dyula", native: "Dyula", code: "dyu" },
  { no: "60", name: "Dzongkha", native: "རྫོང་ཁ", code: "dz" },
  { no: "61", name: "English", native: "English", code: "en" },
  { no: "62", name: "Esperanto", native: "Esperanto", code: "eo" },
  { no: "63", name: "Estonian", native: "Eesti keel", code: "et" },
  { no: "64", name: "Ewe", native: "Eʋe", code: "ee" },
  { no: "65", name: "Faroese", native: "Føroyskt", code: "fo" },
  { no: "66", name: "Fijian", native: "Vosa Vakaviti", code: "fj" },
  { no: "67", name: "Filipino", native: "Filipino", code: "tl" },
  { no: "68", name: "Finnish", native: "Suomi", code: "fi" },
  { no: "69", name: "Fon", native: "Fon", code: "fon" },
  { no: "70", name: "French", native: "Français", code: "fr" },
  { no: "71", name: "Friulian", native: "Furlan", code: "fur" },
  { no: "72", name: "Fulani", native: "Fulfulde", code: "ff" },
  { no: "73", name: "Ga", native: "Ga", code: "gaa" },
  { no: "74", name: "Galician", native: "Galego", code: "gl" },
  { no: "75", name: "Ganda", native: "Luganda", code: "lg" },
  { no: "76", name: "Georgian", native: "ქართული", code: "ka" },
  { no: "77", name: "German", native: "Deutsch", code: "de" },
  { no: "78", name: "Greek", native: "Ελληνικά", code: "el" },
  { no: "79", name: "Guarani", native: "Avañe'ẽ", code: "gn" },
  { no: "80", name: "Gujarati", native: "ગુજરાતી", code: "gu" },
  { no: "81", name: "Haitian Creole", native: "Kreyòl Ayisyen", code: "ht" },
  { no: "82", name: "Hakha Chin", native: "Hakha Chin", code: "ccp" },
  { no: "83", name: "Hausa", native: "Hausa", code: "ha" },
  { no: "84", name: "Hawaiian", native: "ʻŌlelo Hawaiʻi", code: "haw" },
  { no: "85", name: "Hebrew", native: "עברית", code: "he" },
  { no: "86", name: "Hiligaynon", native: "Hiligaynon", code: "hil" },
  { no: "87", name: "Hindi", native: "हिन्दी", code: "hi" },
  { no: "88", name: "Hmong", native: "Hmoob", code: "hmn" },
  { no: "89", name: "Hungarian", native: "Magyar", code: "hu" },
  { no: "90", name: "Hunsrik", native: "Hunsrückisch", code: "huns" },
  { no: "91", name: "Iban", native: "Iban", code: "iban" },
  { no: "92", name: "Icelandic", native: "Íslenska", code: "is" },
  { no: "93", name: "Igbo", native: "Igbo", code: "ig" },
  { no: "94", name: "Iloko", native: "Ilokano", code: "ilo" },
  { no: "95", name: "Indonesian", native: "Bahasa Indonesia", code: "id" },
  { no: "96", name: "Irish", native: "Gaeilge", code: "ga" },
  { no: "97", name: "Italian", native: "Italiano", code: "it" },
  { no: "98", name: "Jamaican Patois", native: "Jamaican Patois", code: "jam" },
  { no: "99", name: "Japanese", native: "日本語", code: "ja" },
  { no: "100", name: "Javanese", native: "ꦧꦱꦗꦮ", code: "jv" },
  { no: "101", name: "Jingpo", native: "Jinghpaw", code: "jpn" },
  { no: "102", name: "Kalaallisut", native: "Kalaallit oqaasii", code: "kl" },
  { no: "103", name: "Kannada", native: "ಕನ್ನಡ", code: "kn" },
  { no: "104", name: "Kanuri", native: "Kanuri", code: "kr" },
  { no: "105", name: "Kazakh", native: "Қазақ", code: "kk" },
  { no: "106", name: "Khasi", native: "Ka Khasi", code: "kha" },
  { no: "107", name: "Khmer", native: "ភាសាខ្មែរ", code: "km" },
  { no: "108", name: "Kinyarwanda", native: "Ikinyarwanda", code: "rw" },
  { no: "109", name: "Kituba", native: "KiKituba", code: "ktz" },
  { no: "110", name: "Kokborok", native: "𑄖𑄣𑄇𑄧𑄟", code: "kok" },
  { no: "111", name: "Komi", native: "Коми", code: "kv" },
  { no: "112", name: "Kongo", native: "Kikongo", code: "kg" },
  { no: "113", name: "Konkani", native: "कोंकणी", code: "kn" },
  { no: "114", name: "Korean", native: "한국어", code: "ko" },
  { no: "115", name: "Krio", native: "Krio", code: "kri" },
  { no: "116", name: "Kurdish", native: "Kurdî", code: "ku" },
  { no: "117", name: "Kyrgyz", native: "Кыргызча", code: "ky" },
  { no: "118", name: "Lao", native: "ລາວ", code: "lo" },
  { no: "119", name: "Latgalian", native: "Latgaliešu", code: "ltg" },
  { no: "120", name: "Latin", native: "Latina", code: "la" },
  { no: "121", name: "Latvian", native: "Latviešu", code: "lv" },
  { no: "122", name: "Ligurian", native: "Ligure", code: "lij" },
  { no: "123", name: "Limburgish", native: "Limburgs", code: "li" },
  { no: "124", name: "Lingala", native: "Lingála", code: "ln" },
  { no: "125", name: "Lithuanian", native: "Lietuvių", code: "lt" },
  { no: "126", name: "Lombard", native: "Lumbard", code: "lmo" },
  { no: "127", name: "Luo", native: "Dholuo", code: "luo" },
  { no: "128", name: "Luxembourgish", native: "Lëtzebuergesch", code: "lb" },
  { no: "129", name: "Macedonian", native: "Македонски", code: "mk" },
  { no: "130", name: "Madurese", native: "Basa Mathura", code: "mad" },
  { no: "131", name: "Maithili", native: "मैथिली", code: "mai" },
  { no: "132", name: "Makasar", native: "Basa Makassar", code: "mak" },
  { no: "133", name: "Malagasy", native: "Malagasy", code: "mg" },
  { no: "134", name: "Malay", native: "Bahasa Melayu", code: "ms" },
  { no: "135", name: "Malay (Arabic)", native: "Bahasa Melayu (Arab)", code: "msa" },
  { no: "136", name: "Malayalam", native: "മലയാളം", code: "ml" },
  { no: "137", name: "Maltese", native: "Il-L-Istudji", code: "mt" },
  { no: "138", name: "Mam", native: "Mam", code: "mam" },
  { no: "139", name: "Manipuri (Meitei Mayek)", native: "ꯃꯇꯦꯇꯕꯤ", code: "mni" },
  { no: "140", name: "Manx", native: "Gaelg", code: "gv" },
  { no: "141", name: "Māori", native: "Te Reo Māori", code: "mi" },
  { no: "142", name: "Marathi", native: "मराठी", code: "mr" },
  { no: "143", name: "Marshallese", native: "Kajin M̧ajeļ", code: "mh" },
  { no: "144", name: "Marwari", native: "मारवाड़ी", code: "mwr" },
  { no: "145", name: "Meadow Mari", native: "Марий", code: "mhr" },
  { no: "146", name: "Minangkabau", native: "Minangkabau", code: "min" },
  { no: "147", name: "Mizo", native: "Mizo", code: "mzn" },
  { no: "148", name: "Mongolian", native: "Монгол", code: "mn" },
  { no: "149", name: "Morisyen", native: "Morisyen", code: "mfe" },
  { no: "150", name: "Nahuatl (Eastern Huasteca)", native: "Nawat", code: "nah" },
  { no: "151", name: "Ndau", native: "ChiNdau", code: "nd" },
  { no: "152", name: "Nepalbhasa (Newari)", native: "नेपाल भाषा", code: "new" },
  { no: "153", name: "Nepali", native: "नेपाली", code: "ne" },
  { no: "154", name: "Nko", native: "ߒߞߏ", code: "nqo" },
  { no: "155", name: "Northern Sami", native: "Davvisámegiella", code: "se" },
  { no: "156", name: "Northern Sotho", native: "Sesotho sa Leboa", code: "nso" },
  { no: "157", name: "Norwegian", native: "Norsk", code: "no" },
  { no: "158", name: "Nuer", native: "Nuer", code: "nu" },
  { no: "159", name: "Nyanja", native: "Chichewa", code: "ny" },
  { no: "160", name: "Occitan", native: "Occitan", code: "oc" },
  { no: "161", name: "Odia", native: "ଓଡ଼ିଆ", code: "or" },
  { no: "162", name: "Oromo", native: "Afaan Oromoo", code: "om" },
  { no: "163", name: "Ossetic", native: "Ирон", code: "os" },
  { no: "164", name: "Pampanga", native: "Kapampangan", code: "pam" },
  { no: "165", name: "Pangasinan", native: "Pangasinan", code: "pag" },
  { no: "166", name: "Papiamento", native: "Papiamentu", code: "pap" },
  { no: "167", name: "Pashto", native: "پښتو", code: "ps" },
  { no: "168", name: "Persian", native: "فارسی", code: "fa" },
  { no: "169", name: "Polish", native: "Polski", code: "pl" },
  { no: "170", name: "Portuguese", native: "Português", code: "pt" },
  { no: "171", name: "Portuguese (Portugal)", native: "Português (Portugal)", code: "pt-pt" },
  { no: "172", name: "Punjabi", native: "ਪੰਜਾਬੀ", code: "pa" },
  { no: "173", name: "Punjabi (Arabic)", native: "پنجابی", code: "pa-arab" },
  { no: "174", name: "Q'eqchi'", native: "Q'eqchi'", code: "qtc" },
  { no: "175", name: "Quechua", native: "Runa Simi", code: "qu" },
  { no: "176", name: "Romanian", native: "Română", code: "ro" },
  { no: "177", name: "Romany", native: "Romani", code: "rom" },
  { no: "178", name: "Rundi", native: "Kirundi", code: "rn" },
  { no: "179", name: "Russian", native: "Русский", code: "ru" },
  { no: "180", name: "Samoan", native: "Gagana Samoa", code: "sm" },
  { no: "181", name: "Sango", native: "Sängö", code: "sg" },
  { no: "182", name: "Sanskrit", native: "संस्कृत", code: "sa" },
  { no: "183", name: "Santali (Latin)", native: "Santali", code: "sat" },
  { no: "184", name: "Scottish Gaelic", native: "Gàidhlig", code: "gd" },
  { no: "185", name: "Serbian", native: "Српски", code: "sr" },
  { no: "186", name: "Seselwa Creole French", native: "Seselwa", code: "crs" },
  { no: "187", name: "Shan", native: "ၽႃႇတႆႇ", code: "shn" },
  { no: "188", name: "Shona", native: "ChiShona", code: "sn" },
  { no: "189", name: "Sicilian", native: "Sicilianu", code: "scn" },
  { no: "190", name: "Silesian", native: "Ślōnskŏ", code: "szl" },
  { no: "191", name: "Sindhi", native: "سنڌي", code: "sd" },
  { no: "192", name: "Sinhala", native: "සිංහල", code: "si" },
  { no: "193", name: "Slovak", native: "Slovenčina", code: "sk" },
  { no: "194", name: "Slovenian", native: "Slovenščina", code: "sl" },
  { no: "195", name: "Somali", native: "Soomaali", code: "so" },
  { no: "196", name: "South Ndebele", native: "SiNdebele", code: "nr" },
  { no: "197", name: "Southern Sotho", native: "Sesotho", code: "st" },
  { no: "198", name: "Spanish", native: "Español", code: "es" },
  { no: "199", name: "Sundanese", native: "Basa Sunda", code: "su" },
  { no: "200", name: "Susu", native: "Susu", code: "sus" },
  { no: "201", name: "Swahili", native: "Kiswahili", code: "sw" },
  { no: "202", name: "Swati", native: "siSwati", code: "ss" },
  { no: "203", name: "Swedish", native: "Svenska", code: "sv" },
  { no: "204", name: "Tahitian", native: "Reo Tahiti", code: "ty" },
  { no: "205", name: "Tajik", native: "Тоҷикӣ", code: "tg" },
  { no: "206", name: "Tamazight", native: "ⵜⴰⵎⴰⵣⵉⵖⵜ", code: "tzm" },
  { no: "207", name: "Tamazight (Tifinagh)", native: "ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵜⵉⴼⵉⵏⴰⵖ)", code: "tzm-tif" },
  { no: "208", name: "Tamil", native: "தமிழ்", code: "ta" },
  { no: "209", name: "Tatar", native: "Татар", code: "tt" },
  { no: "210", name: "Telugu", native: "తెలుగు", code: "te" },
  { no: "211", name: "Tetum", native: "Tetum", code: "tet" },
  { no: "212", name: "Thai", native: "ไทย", code: "th" },
  { no: "213", name: "Tibetan", native: "བོད་ཡིག", code: "bo" },
  { no: "214", name: "Tigrinya", native: "ትግርኛ", code: "ti" },
  { no: "215", name: "Tiv", native: "Tiv", code: "tiv" },
  { no: "216", name: "Tok Pisin", native: "Tok Pisin", code: "tpi" },
  { no: "217", name: "Tongan", native: "faka Tonga", code: "to" },
  { no: "218", name: "Tsonga", native: "Xitsonga", code: "ts" },
  { no: "219", name: "Tswana", native: "Setswana", code: "tn" },
  { no: "220", name: "Tulu", native: "ತೂಳು", code: "tcy" },
  { no: "221", name: "Tumbuka", native: "Chitumbuka", code: "tum" },
  { no: "222", name: "Turkish", native: "Türkçe", code: "tr" },
  { no: "223", name: "Turkmen", native: "Türkmençe", code: "tk" },
  { no: "224", name: "Twi", native: "Twi", code: "tw" },
  { no: "225", name: "Ukrainian", native: "Українська", code: "uk" },
  { no: "226", name: "Urdu", native: "اردو", code: "ur" },
  { no: "227", name: "Uyghur", native: "ئۇيغۇرچە", code: "ug" },
  { no: "228", name: "Uzbek", native: "Oʻzbek", code: "uz" },
  { no: "229", name: "Venda", native: "Tshivenḓa", code: "ve" },
  { no: "230", name: "Vietnamese", native: "Tiếng Việt", code: "vi" },
  { no: "231", name: "Wolof", native: "Wolof", code: "wo" },
  { no: "232", name: "Xhosa", native: "isiXhosa", code: "xh" },
  { no: "233", name: "Yiddish", native: "ייִדיש", code: "yi" },
  { no: "234", name: "Yoruba", native: "Yorùbá", code: "yo" },
  { no: "235", name: "Zaza", native: "Zazaki", code: "zza" },
  { no: "236", name: "Zulu", native: "isiZulu", code: "zu" } 
]
